apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-redis
spec:
  selector:
    matchLabels:
      app: nginx
  #replicas: 2
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80