apiVersion: v1
kind: Service
metadata:
  name: service
  labels:
    app: service
spec:
  ports:
    - port: 3232
  selector:
    app: service
    tier: frontend
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: despliegue-service
  labels:
    app: service
spec:
  selector:
    matchLabels:
      app: service
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: service
        tier: frontend
    spec:
      containers:
        - name: contenedor-principal
          image: docker.io/karthik3030/mongoscaleserver:latest2
          imagePullPolicy: Always
          args:
            - app
          ports:
            - containerPort: 3232
              name: service
          resources:
            limits:
              cpu: "0.3"
