apiVersion: batch/v1
kind: Job
metadata:
  name: publicador-rabbitmq
spec:
  template:
    spec:
      containers:
        - name: cliente-rabbitmq
          image: ghcr.io/kedacore/rabbitmq-client:v1.0
          imagePullPolicy: Always
          command:
            [
              "send",  # Comando para enviar mensajes
              "amqp://user:PASSWORD@rabbitmq.default.svc.cluster.local:5672",  # URL de conexión a RabbitMQ
              "300",  # Nmero de mensajes a enviar
            ]
      restartPolicy: Never  # Política de reinicio del contenedor
  backoffLimit: 4  # Límite de reintentos en caso de fallo
